name: Deploy ADHDashboard to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  call-deploy:
    uses: devknowsdev/workspace-meta/.github/workflows/reusable-deploy-adhd.yml@main
    with:
      build_dir: '.'
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
